# docker-compose.yml
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    # depends_on:
    #   - redis
    command: python manage.py runserver 0.0.0.0:8000

    networks:
      - mynetwork
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: my-redis-container-celery
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    command: redis-server

  celery_worker:
    build:
      context: .
      dockerfile: dockerfile.celery_worker
    command: celery -A myproject worker --loglevel=info
    networks:
      - mynetwork
    volumes:
      - .:/app

  celery_beat:
    build:
      context: .
      dockerfile: dockerfile.celery_beat
    ports:
      - "5555:5555"
    command: celery -A myproject beat --loglevel=info
    networks:
      - mynetwork
    volumes:
      - .:/app

networks:
  mynetwork:
    driver: bridge
